### ISSUE TITLE
'Model' object has no attribute '_cached_numerical_components'

### ISSUE THREAD

**Issue by Jhsmit** [tBuLi/symfit#186]
Using the current master version (43b77e26892089a3571d6693e7105c6fe3128712) I get several errors when running the example from the readme file. Executing the readme example with a `CallableNumericalModel` doesnt give any problems.

```
Traceback (most recent call last):
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\support.py", line 214, in __get__
    return getattr(obj, self.cache_attr)
AttributeError: 'Model' object has no attribute '_cached_numerical_components'
```

and 

```
Traceback (most recent call last):
  File "C:/Users/Smit/PycharmProjects/CC_Playground/dev/symfit/simple_test.py", line 14, in <module>
    fit_result = fit.execute()
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\fit.py", line 1537, in execute
    minimizer_ans = self.minimizer.execute(**minimize_options)
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\minimizers.py", line 339, in execute
    return super(ScipyGradientMinimize, self).execute(jacobian=self.wrapped_jacobian, **minimize_options)
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\support.py", line 355, in wrapped_func
    return func(*bound_args.args, **bound_args.kwargs)
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\minimizers.py", line 277, in execute
    **minimize_options
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\_minimize.py", line 597, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\optimize.py", line 963, in _minimize_bfgs
    gfk = myfprime(x0)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\optimize.py", line 723, in approx_fprime
    return _approx_fprime_helper(xk, f, epsilon, args=args)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\optimize.py", line 657, in _approx_fprime_helper
    f0 = f(*((xk,) + args))
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\scipy\optimize\optimize.py", line 293, in function_wrapper
    return function(*(wrapper_args + args))
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\minimizers.py", line 254, in wrapped_func
    return np.array(func(**parameters))
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\support.py", line 355, in wrapped_func
    return func(*bound_args.args, **bound_args.kwargs)
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\objectives.py", line 151, in __call__
    evaluated_func = self.model(**jac_kwargs)
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\fit.py", line 334, in __call__
    return Ans(*self.eval_components(**bound_arguments.arguments))
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\fit.py", line 296, in eval_components
    return [expr(*args, **kwargs) for expr in self.numerical_components]
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\support.py", line 217, in __get__
    setattr(obj, self.cache_attr, self.fget(obj))
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\fit.py", line 457, in numerical_components
    return [sympy_to_py(expr, self.independent_vars, self.params) for expr in self.values()]
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\fit.py", line 457, in <listcomp>
    return [sympy_to_py(expr, self.independent_vars, self.params) for expr in self.values()]
  File "c:\users\smit\pycharmprojects\symfit_numerical\symfit\core\support.py", line 91, in sympy_to_py
    return lambdify((vars + params), func, modules='numpy', dummify=False)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\utilities\lambdify.py", line 470, in lambdify
    funcstr = funcprinter.doprint(funcname, args, expr)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\utilities\lambdify.py", line 675, in doprint
    argstrs, expr = self._preprocess(args, expr)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\utilities\lambdify.py", line 740, in _preprocess
    argrep = self._argrepr(arg)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\printing\codeprinter.py", line 101, in doprint
    lines = self._print(expr).splitlines()
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\printing\printer.py", line 287, in _print
    return getattr(self, printmethod)(expr, **kwargs)
  File "C:\Miniconda3\envs\cc_symfit\lib\site-packages\sympy\printing\codeprinter.py", line 345, in _print_Variable
    return self._print(expr.symbol)
AttributeError: 'Variable' object has no attribute 'symbol'
```

**Comment by Jhsmit** [comment]
This error is confusing me a lot. When I run pytest on a checkout of the current master I get no errors. But when I try to run a simple fitting problem I get these errors for some reason.

I've installed the symfit master in conda virtual env by:

0) activate new conda virtual env
1) git clone the master
2) Change pbr=True to pbr=False in setup.py (otherwise errors)
3) pip install -e <foldername>

This usually works perfectly fine. Also if I manually copy the symfit directory to site-packages directory I get the same error. 

What is the best way install the current master of symfit? 
Maybe I should make another fresh conda env. Tests also run fine on windows: https://ci.appveyor.com/project/Jhsmit/symfit

**Comment by tBuLi** [comment]
Can you check your sympy version? The latter error sounds to me like #172. Try installing sympy 1.1.1 if you use a newer version.

In regards to the first traceback, let me know if that persists.

**Comment by Jhsmit** [comment]
yep, both errors were from using sympy v1.3. Didnt run into this before because I was only testing with CallallbeNumericalModels
